### PR TITLE
Fix for missing default rake task

### PR DESCRIPTION
**Pull request by andrewgarner**
To fix deploy failures:

```
rake aborted!
Don't know how to build task 'default' (see --tasks)
```

### CODE REVIEW

**Comment by benthorner** [comment]
I'm getting '0 files inspected, no offenses detected' when I run rake lint, even when I modify a file.

**Comment by benthorner** [comment]
I modified app/admin/.... I would expect it to inspect the file. I also can't see the --diff option in the CLI doc.

**Comment by andrewgarner** [comment]
Unfortunately you have to go and read the source code to understand the behaviour – https://github.com/alphagov/govuk-lint/blob/master/lib/govuk/lint/diff.rb

Essentially the diff is files you have changed and committed.

**Comment by benthorner** [comment]
I have to change it to 'govuk-lint-ruby --cache=true --format clang' to get it to do anything, which then prints out that we've got 4 new violations in delete.rake on master.

**Pull request merged**
